### ISSUE TITLE
회의록

### ISSUE THREAD

**Issue by ordinaryhan** [KingProjectPoison/Project_Poison#3]
2018.07.05(목) 1차 회의 진행

[1차 회의]
- 제작 툴은 유니티, 플랫폼은 안드로이드
- 미니게임 3가지 (사다리 미로, 보글보글, 쿠키런) 세부 기획
- 맵 디자인 구상해보기 (~2018.07.06)
- 유니티 구현 시작
- 그래픽 시작

**Comment by ordinaryhan** [comment]
2018.07.19(목) 2차 회의 진행

[2차 회의] - 2주간 할 일

1. 기획 : 시작화면 애니메이션, 각 스테이지 별 스토리 대화창
1. 그래픽 : 게임 오브젝트 그리기 (선 따기)
1. 미니게임1 : 화면 어둡게 하기 + 힌트 구현
1. 미니게임2 : 이동 수정
1. 미니게임3 : 아이템 랜덤 생성 + 친구 이동 패턴 구현

**Comment by ordinaryhan** [comment]
2018.08.02(목) 3차 회의 진행

[3차 회의] - 1주간 할 일
1. 기획자님 : 사운드 찾기
1. 그래픽님 - 2주간 할 일 : 전체 스케치 완료 (되도록 채색까지)
1. 미니게임 1 : 1차 완료
1. 미니게임 2 : 적 공격 패턴 추가, 점프 고민
1. 미니게임 3 : 핸드폰 5초 아이템 랜덤 생성 (하나씩), 친구/주인공 깜박이기
- 미니게임1, 미니게임2 그래픽 목록 작성해서 그래픽님한테 보내기 (13일까지)

**Comment by ordinaryhan** [comment]
2018.08.09(목) 4차 회의 진행

[4차 회의] - 1주간 할 일 (다음주는 동아리 최종발표!!)
1. 기획자님 : 브금 확정, 중간 합치기 (주말)
1. 그래픽님 : 전체 스케치 완료 (되도록 채색까지)
1. 미니게임1 : 빛 비추기 완성, 그래픽 목록 보내기(오늘)
1. 미니게임2 : 공격 패턴 추가
1. 미니게임3 : 친구 패턴 완성

**Comment by hanna-lee-or** [comment]
2018-09-08 최종발표 완료
